// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-forms/BlueprintTech.tsx": () => import("../components/mockups/login-forms/BlueprintTech.tsx"),
  "./components/mockups/login-forms/FieldSun.tsx": () => import("../components/mockups/login-forms/FieldSun.tsx"),
  "./components/mockups/login-forms/MidnightCraft.tsx": () => import("../components/mockups/login-forms/MidnightCraft.tsx")
};
